In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import math

In [18]:
df = pd.read_csv('./Pokemon.csv')
df2 =  df.sort_values("Type 1")
df.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [25]:
number_of_Water = 50
number_of_normal = 50

total_train = number_of_Water + number_of_normal


df_water = df[df['Type 1'] =='Water' ]
df_Normal = df[df['Type 1'] =='Normal']


total = pd.concat([df_water,df_Normal],axis=0)


In [4]:
a = (train['Type 1']=='Water').values
a.shape
train.head(100)

#                     Name  Type 1    Type 2  Total   HP  Attack  \
9      7                 Squirtle   Water       NaN    314   44      48   
10     8                Wartortle   Water       NaN    405   59      63   
11     9                Blastoise   Water       NaN    530   79      83   
12     9  BlastoiseMega Blastoise   Water       NaN    630   79     103   
59    54                  Psyduck   Water       NaN    320   50      52   
60    55                  Golduck   Water       NaN    500   80      82   
65    60                  Poliwag   Water       NaN    300   40      50   
66    61                Poliwhirl   Water       NaN    385   65      65   
67    62                Poliwrath   Water  Fighting    510   90      95   
78    72                Tentacool   Water    Poison    335   40      40   
79    73               Tentacruel   Water    Poison    515   80      70   
85    79                 Slowpoke   Water   Psychic    315   90      65   
86    80                  Slowbro   Water   Psychic    490   95      75   
87    80      SlowbroMega Slowbro   Water   Psychic    590   95      75   
93    86                     Seel   Water       NaN    325   65      45   
94    87                  Dewgong   Water       Ice    475   90      70   
97    90                 Shellder   Water       NaN    305   30      65   
98    91                 Cloyster   Water       Ice    525   50      95   
106   98                   Krabby   Water       NaN    325   30     105   
107   99                  Kingler   Water       NaN    475   55     130   
125  116                   Horsea   Water       NaN    295   30      40   
126  117                   Seadra   Water       NaN    440   55      65   
127  118                  Goldeen   Water       NaN    320   45      67   
128  119                  Seaking   Water       NaN    450   80      92   
129  120                   Staryu   Water       NaN    340   30      45   
130  121                  Starmie   Water   Psychic    520   60      75   
139  129                 Magikarp   Water       NaN    200   20      10   
140  130                 Gyarados   Water    Flying    540   95     125   
141  130    GyaradosMega Gyarados   Water      Dark    640   95     155   
142  131                   Lapras   Water       Ice    535  130      85   
..   ...                      ...     ...       ...    ...  ...     ...   
143  132                    Ditto  Normal       NaN    288   48      48   
144  133                    Eevee  Normal       NaN    325   55      55   
148  137                  Porygon  Normal       NaN    395   65      60   
155  143                  Snorlax  Normal       NaN    540  160     110   
175  161                  Sentret  Normal       NaN    215   35      46   
176  162                   Furret  Normal       NaN    415   85      76   
177  163                 Hoothoot  Normal    Flying    262   60      30   
178  164                  Noctowl  Normal    Flying    442  100      50   
188  174                Igglybuff  Normal     Fairy    210   90      30   
205  190                    Aipom  Normal       NaN    360   55      70   
218  203                Girafarig  Normal   Psychic    455   70      80   
221  206                Dunsparce  Normal       NaN    415  100      70   
234  216                Teddiursa  Normal       NaN    330   60      80   
235  217                 Ursaring  Normal       NaN    500   90     130   
252  233                 Porygon2  Normal       NaN    515   85      80   
253  234                 Stantler  Normal       NaN    465   73      95   
254  235                 Smeargle  Normal       NaN    250   55      20   
260  241                  Miltank  Normal       NaN    490   95      80   
261  242                  Blissey  Normal       NaN    540  255      10   
286  263                Zigzagoon  Normal       NaN    240   38      30   
287  264                  Linoone  Normal       NaN    420   78      70   
299  276                  Taillo

In [5]:
y_heat=[]
for i in range(len(a)):
    if a[i]==True :
        y_heat.append(1)
    else :
        y_heat.append(0)

In [6]:
Total_matrix_water =   np.array(train['Total'])
HP_matrix_water =      np.array(train['HP'])
Attack_matrix_water =  np.array(train['Attack'])
Defense_matrix_water = np.array(train['Defense'])
SpAtk_matrix_water =   np.array(train['Sp. Atk'])
SpDef_matrix_water =   np.array(train['Sp. Def'])
Speed_matrix_water =   np.array(train['Speed'])

train_data = np.vstack((Total_matrix_water,
                            HP_matrix_water,
                            Attack_matrix_water,
                            Defense_matrix_water,
                            SpAtk_matrix_water,
                            SpDef_matrix_water,
                            Speed_matrix_water)).T

train_data[0]

array([314,  44,  48,  65,  50,  64,  43], dtype=int64)

In [7]:
Total_matrix_water =   np.array(test['Total'])
HP_matrix_water =      np.array(test['HP'])
Attack_matrix_water =  np.array(test['Attack'])
Defense_matrix_water = np.array(test['Defense'])
SpAtk_matrix_water =   np.array(test['Sp. Atk'])
SpDef_matrix_water =   np.array(test['Sp. Def'])
Speed_matrix_water =   np.array(test['Speed'])

test_data = np.vstack((Total_matrix_water,
                            HP_matrix_water,
                            Attack_matrix_water,
                            Defense_matrix_water,
                            SpAtk_matrix_water,
                            SpDef_matrix_water,
                            Speed_matrix_water)).T

test_data[0]

array([560,  70, 140,  70, 110,  65, 105], dtype=int64)

In [13]:
 w, v = np.linalg.eig(test_data)

LinAlgError: Last 2 dimensions of the array must be square

In [10]:
w

array([1., 2., 3.])

In [11]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
v[0]

array([1., 0., 0.])

In [ ]:
df[df['Type 1'] =='Water' ]
df_Normal = df[df['Type 1'] =='Normal']

In [31]:
(df['Type 1'] =='Normal' and df['Type 1'] =='Water')

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().