In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import math
import matplotlib.pyplot as plt

from sklearn import decomposition
from numpy.random import RandomState
from keras.datasets import mnist
from keras.utils import np_utils
n_components = 6

In [62]:
df = pd.read_csv('./Pokemon.csv')
df2 =  df.sort_values("Type 1")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
#             800 non-null int64
Name          800 non-null object
Type 1        800 non-null object
Type 2        414 non-null object
Total         800 non-null int64
HP            800 non-null int64
Attack        800 non-null int64
Defense       800 non-null int64
Sp. Atk       800 non-null int64
Sp. Def       800 non-null int64
Speed         800 non-null int64
Generation    800 non-null int64
Legendary     800 non-null bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB


In [63]:
number_of_Water = 50
number_of_normal = 50

total_train = number_of_Water + number_of_normal
mask_water = df['Type 1'] =='Water'
mask_normal= df['Type 1'] =='Normal'

total = df[mask_water | mask_normal]


In [64]:
matrix_mean = [total['HP'].mean(),
               total['Attack'].mean(),
               total['Defense'].mean(),
               total['Sp. Atk'].mean(),
               total['Sp. Def'].mean(),
               total['Speed'].mean()]

In [65]:
HP_matrix =      np.array(total['HP']-total['HP'].mean())
Attack_matrix =  np.array(total['Attack']-total['Attack'].mean())
Defense_matrix = np.array(total['Defense']- total['Defense'].mean())
SpAtk_matrix =   np.array(total['Sp. Atk']-total['Sp. Atk'].mean())
SpDef_matrix =   np.array(total['Sp. Def']-total['Sp. Def'].mean())
Speed_matrix =   np.array(total['Speed']- total['Speed'].mean())

total_data = np.vstack((HP_matrix,
                        Attack_matrix,
                        Defense_matrix,
                        SpAtk_matrix,
                        SpDef_matrix,
                        Speed_matrix)).T


In [72]:
estimators = [
    ('Eigenfaces - PCA using randomized SVD',
         decomposition.PCA(n_components=6,whiten=True)),

    ('Non-negative components - NMF',
         decomposition.NMF(n_components=6, init='nndsvda', tol=5e-3))
]

In [73]:
for name, estimator in estimators:
    print("Extracting the top %d %s..." % (n_components, name))
    print(total_data.shape)
    estimator.fit(total_data)
    components_ = estimator.components_
    print(components_)

Extracting the top 6 Eigenfaces - PCA using randomized SVD...
(210, 6)
[[ 0.39537644  0.45571409  0.40340947  0.47915373  0.44034356  0.22309683]
 [ 0.74652147 -0.38245439 -0.27623874 -0.04010765  0.22876458 -0.4076575 ]
 [-0.33046285 -0.15008681  0.50678577  0.1949865   0.15148774 -0.74193542]
 [-0.31370776 -0.59702372 -0.21155115  0.4597324   0.4287557   0.3243623 ]
 [ 0.04629006  0.13731801 -0.33379975  0.71842285 -0.5575581  -0.20143558]
 [ 0.27680707 -0.49823057  0.58986861  0.05742882 -0.4859149   0.29629007]]
Extracting the top 6 Non-negative components - NMF...
(210, 6)
[[ 13.31024637  51.81209478  16.4983078    0.          63.21738593
    0.        ]
 [  0.         203.08486838 104.69055665  63.06375047   0.
  226.26858916]
 [132.88927672 289.48350649 147.09853848  20.23670453   0.
    0.        ]
 [ 52.95073537  37.95690659  46.66532515  90.02407348  25.91632049
   32.57531819]
 [ 37.74172169  63.07868152  42.42712273  37.57256965  73.97775992
   53.62652131]
 [ 73.77986289  

In [111]:
w,h = np.linalg.eig(np.cov(total_data.T))

In [112]:
h.shape

(6, 6)

In [126]:
c = np.dot(h,total_data.T)

In [127]:
c.shape

(6, 210)

In [132]:
result = np.dot(h,c)

In [134]:
result.shape

(6, 210)

In [144]:
result

array([[ 37.63624438,  51.24701618,  68.66955063, ...,  60.57843149,
         46.35389046,  81.00463476],
       [ 23.2167725 ,  27.7277347 ,  36.09240898, ...,  15.73711921,
         24.17076422,  32.85176662],
       [ 27.14370048,  34.90844689,  44.4356534 , ...,  40.8559956 ,
         25.50819121,  12.02940347],
       [ 27.83398707,  38.08611803,  50.91387154, ...,  54.35437232,
         35.0214086 ,  66.67698489],
       [ 92.8155977 , 115.92761133, 147.82619132, ..., 102.50667933,
         93.16549417, 149.63669264],
       [ 69.48559632,  91.2992494 , 122.5826186 , ..., 138.94375569,
         71.6387801 ,  96.40199133]])

In [145]:
total_data

array([[ 44,  48,  65,  50,  64,  43],
       [ 59,  63,  80,  65,  80,  58],
       [ 79,  83, 100,  85, 105,  78],
       ...,
       [ 75,  80,  60,  65,  90, 102],
       [ 50,  53,  62,  58,  63,  44],
       [ 71,  73,  88, 120,  89,  59]], dtype=int64)